-- ============================================================
-- schema-principles.sql — replaces verbatim exemplar storage with
-- distilled, generalized reply logic.
--
-- exemplar_replies fed literal {customer_message, human_reply} pairs
-- into the prompt as few-shot "Customer: X / Reply: Y" examples —
-- which taught Clerk to imitate exact wording across different
-- customers. reply_principles instead stores the underlying
-- reasoning/policy behind a correction or human resolution, distilled
-- once via an LLM call (see distillPrinciple() in widget.mjs), so
-- future drafts apply the same LOGIC in fresh wording each time.
--
-- exemplar_replies is left in place (non-destructive) but is no
-- longer written to or read from anywhere in the app.
-- Run AFTER schema-tutor.sql.
-- ============================================================

create table reply_principles (
  id bigint generated by default as identity primary key,
  merchant_id uuid not null references merchants(id) on delete cascade,
  category text,
  principle text not null,
  source_ticket_hash text,
  created_at timestamptz not null default now()
);
create index reply_principles_merchant_idx on reply_principles (merchant_id, created_at desc);

alter table reply_principles enable row level security;
create policy "own reply_principles" on reply_principles for all
  using (merchant_id = auth_merchant_id());

comment on table exemplar_replies is 'DEPRECATED — superseded by reply_principles; no longer written to or read from.';
